apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      initContainers:
        - name: "sqlconnection-starter"
          image: "mysql:8.4"
          imagePullPolicy: IfNotPresent
          env:
            - name: MB_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_HOST
            - name: MB_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-user
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-password
          command:
            - sh
            - -c
            - >
              until mysql -h "$MB_DB_HOST" -P "$MB_DB_PORT" -u"$DB_USER" -p"$MB_DB_PASS"
              -e 'SELECT 1' >/dev/null 2>&1;
              do echo "waiting for db"; sleep 3; done

      containers:
        - name: metabase
          image: metabase/metabase:v0.50.20.5
          imagePullPolicy: Always
          env:
            # Metabase
            - name: MB_DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_TYPE
            - name: MB_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-name
            - name: MB_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_PORT
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-user
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-password
            - name: MB_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: metabase-config
                  key: MB_DB_HOST


            - name: MB_SITE_URL
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: MB_SITE_URL
            - name: MB_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: MB_ADMIN_EMAIL
            - name: MB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: MB_ADMIN_PASSWORD

          ports:
            - name: metabase
              containerPort: 3000

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10

      volumes:
        - name: secret-volume
          secret:
            secretName: mysql-secret
        - name: config-volume
          configMap:
            name: metabase-config
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: metabase
