apiVersion: v1
kind: Secret
metadata:
  name: metabase-secret
type: Opaque
stringData:
  MB_ADMIN_EMAIL: admintest@example.com
  MB_ADMIN_PASSWORD: testeo123
  MB_SITE_URL: https://santiago-graffigna-web.my.kube.um.edu.ar
